# Generated by Django 4.2.7 on 2023-11-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorfile',
            name='file_text',
        ),
        migrations.AddField(
            model_name='editorfile',
            name='body',
            field=models.JSONField(default=list, help_text='Text stored in file'),
        ),
        migrations.AddField(
            model_name='editorfile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
