# Generated by Django 4.2.4 on 2023-08-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_editorfile_file_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorfile',
            name='author',
            field=models.CharField(default='William Shakespeare', help_text='Username of file creator', max_length=20),
            preserve_default=False,
        ),
    ]
