# Generated by Django 5.0.4 on 2024-04-06 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorfile',
            name='_id',
            field=models.CharField(default=uuid.uuid4, editable=False, help_text='ID of file', max_length=50, primary_key=True, serialize=False),
        ),
    ]
