# Generated by Django 5.0.4 on 2024-04-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorfile',
            old_name='_id',
            new_name='uid',
        ),
    ]
