# Generated by Django 5.0.4 on 2024-04-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_alter_user_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
