# Generated by Django 5.0.4 on 2024-04-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0006_alter_user_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
    ]
