# Generated by Django 5.0.4 on 2024-04-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_remove_user_prompts_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
