# Generated by Django 5.0.4 on 2024-04-24 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_alter_prompt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='id',
            new_name='uid',
        ),
    ]
