# Generated by Django 5.0.4 on 2024-04-24 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_rename_id_prompt_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
